### ISSUE TITLE
Frontend cannot access argocd even if proxy is configured

### ISSUE THREAD

**Issue by cmoulliard** [q-shift/backstage-playground#11]
## Issue 

Do we have to create a proxy as documented [here](https://github.com/RoadieHQ/roadie-backstage-plugins/tree/main/plugins/frontend/backstage-plugin-argo-cd#how-to-add-argo-cd-project-dependency-to-backstage-app) ?
> Maybe

I added
```
proxy:
  endpoints:
    '/argocd/api':
       target: https://openshift-gitops-server-openshift-gitops.apps.qshift.snowdrop.dev/api/v1
       changeOrigin: true
```
but still no luck ... as front reports such an error 
```
Failed to load resource: the server responded with a status of 404 (Not Found) ==> http://localhost:7007/api/argocd/find/name/my-quarkus-app-dev
```

**Comment by cmoulliard** [comment]
Problem fixed after adding the ARGOCD_AUTH_TOKEN 
```
argocd:
  username: admin
  password: hU5k....BGQDEX
  baseUrl: https://openshift-gitops-server-openshift-gitops.apps.qshift.snowdrop.dev
  appLocatorMethods:
    - type: config
      instances:
        - name: argocdQShift
          url: https://openshift-gitops-server-openshift-gitops.apps.qshift.snowdrop.dev

proxy:
  endpoints:
    '/argocd/api':
      target: https://openshift-gitops-server-openshift-gitops.apps.qshift.snowdrop.dev/api/v1/
      changeOrigin: true
      secure: false
      headers:
        Cookie:
          $env: eyJhbGciO...vad7Jf8dDAYzj-I

```

**Comment by cmoulliard** [comment]
We can curl argocd 
```
curl -s -H "Authorization: Bearer $ARGOCD_TOKEN" https://$ARGOCD_SERVER/api/version | jq .
{
  "Version": "v2.9.2+c5ea5c4",
  "BuildDate": "2023-12-01T19:21:49Z",
  "GitCommit": "c5ea5c4df52943a6fff6c0be181fde5358970304",
  "GitTreeState": "clean",
  "GoVersion": "go1.20.10",
  "Compiler": "gc",
  "Platform": "linux/amd64",
  "KustomizeVersion": "v5.2.1 unknown",
  "HelmVersion": "v3.13.2+g2a2fb3b",
  "KubectlVersion": "v0.24.2",
  "JsonnetVersion": "v0.20.0",
  "ExtraBuildInfo": "{Vendor Information: Red Hat OpenShift GitOps version: v1.11.0}"
}
```

using such request

**Comment by cmoulliard** [comment]
There is something broken with either argocd plugin or backstage or qshift cluster !!
Why ? The following config is working 
```
proxy:
  endpoints:
    '/argocd/api':
      target: https://openshift-gitops-server-openshift-gitops.apps.qshift.snowdrop.dev/api/v1
      changeOrigin: true
      secure: false
      headers:
        # TOKEN => "curl -sk -X POST -H "Content-Type: application/json" -d '{"username": "'${ARGOCD_USER}'","password": "'${ARGOCD_PWD}'"}' "https://$ARGOCD_SERVER/api/v1/session" | jq -r .token"
 # TOKEN is valid for 24h !!!
        Cookie:  argocd.token=eyJhbGciOiJIU...OyE2Mk6TVMPT8lYnyI

argocd:
  baseUrl: https://openshift-gitops-server-openshift-gitops.apps.qshift.snowdrop.dev
  #appLocatorMethods:
  #  - type: config
  #    instances:
  #      - name: argocdQShift
  #        username: admin
  #        password: hU5ksdnFxK1qiH9gflR6jZIbz7BGQDEX
  #        url: https://openshift-gitops-server-openshift-gitops.apps.qshift.snowdrop.dev
```
BUT only if we use this UI component
```
      <EntityLayout.Route path="/cd" title="CD">
        <EntityArgoCDOverviewCard />
      </EntityLayout.Route>
```
AND not
```
       <EntityLayout.Route path="/cd" title="CD">
       <EntityArgoCDHistoryCard />
       </EntityLayout.Route>

```

**Comment by jacobdotcosta** [comment]
Should we temporarily downgrade the frontend package to `"@roadiehq/backstage-plugin-argo-cd": "2.4.1",` as commented on RoadieHQ/roadie-backstage-plugins/issues/1238 ?
@cmoulliard

**Comment by cmoulliard** [comment]
> Should we temporarily downgrade the frontend package to `"@roadiehq/backstage-plugin-argo-cd": "2.4.1",` as

This is what I try to test at the moment but I got a backstage error not related to this issue when I scaffold the project

**Comment by cmoulliard** [comment]
If I only set
```
argocd:
  baseUrl: https://openshift-gitops-server-openshift-gitops.apps.qshift.snowdrop.dev/
  username: admin
  password: hU5ksdnFxK...7BGQDEX
  
AND

proxy:
  endpoints:
    '/argocd/api':
      target: https://openshift-gitops-server-openshift-gitops.apps.qshift.snowdrop.dev/api/v1
      changeOrigin: true
      secure: false
      headers:
        Cookie:
          argocd.token=eyJhbGc  ...
```  
then we can see the argocd UI views + data  BUT scaffolding is failing !!
