### ISSUE TITLE
QUAY_ORG defined as github secret is not passed to a job executed by a PR

### ISSUE THREAD

**Issue by cmoulliard** [q-shift/backstage-playground#110]
## Issue

When we submit a PR (example: https://github.com/q-shift/backstage-playground/pull/95) then the [job](https://github.com/q-shift/backstage-playground/actions/runs/9189444525/workflow?pr=95) building our backstage app + image fails to build/publish an image as the org is missing from the image name `quay.io//xxx`

![Screenshot 2024-05-23 at 14 12 41](https://github.com/q-shift/backstage-playground/assets/463790/d2d85928-84d9-4ac2-b5e8-4eadc7d2efcf)

The github secrets are well defined and includes the `QUAY_ORG`

![Screenshot 2024-05-23 at 14 21 01](https://github.com/q-shift/backstage-playground/assets/463790/e9deff0e-e441-4efb-94c6-f3bb78aafa89)

and defined within the job yaml file as env var => `REGISTRY_ORG: ${{ secrets.QUAY_ORG }}`
```
// https://github.com/q-shift/backstage-playground/blob/main/.github/workflows/build-push-backstage-image.yml
name: Build backstage app, image and push it

on:
  push:
    branches:
      - main
    tags-ignore:
      - v*
  pull_request:
    branches:
      - main

env:
  REGISTRY: quay.io
  REGISTRY_ORG: ${{ secrets.QUAY_ORG }}
```

So, why then the github action is not able to get the env property here `IMAGE_NAME=${{ env.REGISTRY }}/${{ env.REGISTRY_ORG }}/${{ env.BACKSTAGE_IMAGE_NAME }}` within the YAML job ?
```
// https://github.com/q-shift/backstage-playground/blob/main/.github/workflows/build-push-backstage-image.yml

      - name: Push the built image
        run: |
          IMAGE_NAME=${{ env.REGISTRY }}/${{ env.REGISTRY_ORG }}/${{ env.BACKSTAGE_IMAGE_NAME }}
```
![Screenshot 2024-05-27 at 17 51 29](https://github.com/q-shift/backstage-playground/assets/463790/9cdfd6de-16be-49a0-bf6c-fe5b62d93484)

**IMPORTANT**: What it is completely crazy is that such a problem don't occur at all when the job runs after the PR has been merged on main branch

![Screenshot 2024-05-28 at 10 02 45](https://github.com/q-shift/backstage-playground/assets/463790/b9421169-d1e8-40bc-b44f-21585da7506f)

**Comment by cmoulliard** [comment]
I was able to reproduce the error with a simple project and example from: https://docs.github.com/en/actions/learn-github-actions/variables#using-the-vars-context-to-access-configuration-variable-values
```
name: Test vars, secrets - test 1

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  # Setting an environment variable with the value of a configuration variable
  REGISTRY_ORG_VAR: ${{ vars.QUAY_ORG }}
  REGISTRY_ORG_SECRET: ${{ secrets.QUAY_ORG }}

jobs:
  display-variables:
    name: show-variables-secrets
    runs-on: ubuntu-latest
    steps:
      - name: Use variables
        run: |
          echo "Registry org variable: $REGISTRY_ORG_VAR"
          echo "Registry org secret: $REGISTRY_ORG_SECRET"
          
          echo "Env var set from workflow env var: ${{ env.VAR1 }}"
          echo "Env var set from workflow env secret: ${{ env.SECRET1 }}"
        env:
          VAR1: $REGISTRY_ORG_VAR
          SECRET1: $REGISTRY_ORG_SECRET
```
That works very well when the job is executed from the PR pushed on the github repository

![Screenshot 2024-05-28 at 14 09 46](https://github.com/q-shift/backstage-playground/assets/463790/6ec7f4cc-ad5d-42a0-9732-76c450e83441)

BUT that fails using a forked project as reported within this ticket

![Screenshot 2024-05-28 at 14 10 52](https://github.com/q-shift/backstage-playground/assets/463790/2ae5c960-9903-4a30-a449-ea73f66f5f94)
