### ISSUE TITLE
Drop rest-client template ?

### ISSUE THREAD

**Issue by iocanel** [q-shift/backstage-playground#113]
I think that now that we have a more concrete yet generic enough example (the chatbot) that shows how to consume an api, maybe we should drop the rest-client template.

**Comment by cmoulliard** [comment]
As the goal of the `rest-client` template is to:
- Generate a quarkus application using the extensions
```
- io.quarkus:quarkus-rest-jackson
- io.quarkus:quarkus-smallrye-openapi
- io.quarkus:quarkus-smallrye-graphql
- io.quarkus:quarkus-hibernate-orm-rest-data-panache
```
- Add some maven
```
          dependencies:
            - groupId: io.quarkiverse.openapi.generator
              artifactId: quarkus-openapi-generator
              version: 2.4.2
            - groupId: io.quarkus
              artifactId: quarkus-rest-client-jackson
```     
but without the skeleton of an application AND using only the quarkus starters
then it don't really bring more added value
