### ISSUE TITLE
Find a way to properly pass the quarkus version to our helm chart labels

### ISSUE THREAD

**Issue by iocanel** [q-shift/backstage-playground#114]
We need to pass the exact quarkus version as a label to our application deployements. So, we need to somehow extract the version.

Using the version from the QuarkusVersionList is not enough as it only contains major and minor but not micro parts.

Maybe an action that reads the pom and set the value in the helm values.yaml file is needed or something smarter.

**Comment by cmoulliard** [comment]
We can extract the quarkusVersion from what we got as template's parameter using a filter as documented here: https://github.com/q-shift/qshift-templates/issues/48#issuecomment-2037285616

Such a filter can be now registered part of a backendModule as I documented here: https://backstage.io/docs/features/software-templates/writing-templates#custom-filters :-)

**IMPORTANT**: What you are looking for is not to get the version that a user selects using the list (e.g. 3.9, 3.10, 3.11, etc) but the version which has been scaffolded within the pom.xml. 

So my proposition can help if we want to pass as parameter such a version: `3.9` instead of `io.quarkus.platform:3.9` to an action able to fetch and process the templates using nunjucks like the following
```
    - id: gitopsTemplate
      name: Generating GitOps Resources
      action: fetch:template
      input:
        url: manifests/
        copyWithoutTemplating: []
        values:
          quarkusVersion: ${{ parameters.quarkusVersion | extractVersionFromKey }}
```
In this case, we don't need anymore such a code part of the helm file
```
{%- if values.quarkusVersion %}
  {%- set streamKey = values.quarkusVersion %}
  {%- set quarkusVersionArr = streamKey.split(':') %}
  {%- set quarkusVersion = quarkusVersionArr[1] %}
{%- else %}
  {%- set quarkusVersion = '' %}
{%- endif %}
apiVersion: backstage.io/v1alpha1
kind: Component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.component_id }}
  {%- if values.title %}
  title: ${{ values.title }}
  {%- endif %}
  {%- if values.description %}
  description: ${{ values.description }}
  {%- endif %}
  annotations:
...
    app.quarkus.io/quarkus-version: "${{ quarkusVersion }}"
```
So, what you want to get is this quarkus maven version (when declared as property) = https://github.com/ch007m/my-quarkus-todo-app/blob/main/pom.xml#L14 ? Why instead of using `3.9, 3.10, etc ?@iocanel
