### ISSUE TITLE
Kubernetes tab not displayed

### ISSUE THREAD

**Issue by cmoulliard** [q-shift/backstage-playground#15]
## Issue

I created a new component on a backstage's app `1.20.1` where the kubernetes plugin is installed and configured according to the documentation
```
kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - url: https://api.qshift.snowdrop.dev:6443/ # https://kubernetes.default.svc/
          name: ocp-qshift
          skipTLSVerify: true
          authProvider: 'serviceAccount'
          skipMetricsLookup: true
          serviceAccountToken: ey......
```
but we cannot see in the UI (see screenshot) even if the annotation is added to the component
```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-quarkus-app
  description: A cool quarkus app
  annotations:
    argocd/app-name: my-quarkus-app
    backstage.io/kubernetes-id: my-quarkus-app
    backstage.io/kubernetes-namespace: qshift
    backstage.io/source-location: url:https://github.com/ch007m/my-quarkus-app
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: ch007m/
spec:
  type: api
  lifecycle: production
  owner: user:default/guest
```
and resources created on the cluster (see screenshot). 
Here is the outpuit of a pod
```
k get pod/my-quarkus-app-dev-quarkus-template-7c866c6cbc-vqxzv -n qshift -oyaml
apiVersion: v1
kind: Pod
metadata:
  generateName: my-quarkus-app-dev-quarkus-template-7c866c6cbc-
  labels:
    app.kubernetes.io/instance: my-quarkus-app-dev
    app.kubernetes.io/name: quarkus-template
    backstage.io/kubernetes-id: my-quarkus-app <<== CORRECT VALUE MATCHING COMPONENT LABEL
  name: my-quarkus-app-dev-quarkus-template-7c866c6cbc-vqxzv
  namespace: qshift
...
```

Backstage backend don't report errors and plugin is well loaded by the backend
```
2024-01-31T20:46:05.958Z kubernetes info Initializing Kubernetes backend type=plugin
2024-01-31T20:46:05.959Z kubernetes info action=LoadingCustomResources numOfCustomResources=0 type=plugin
```

According to the documentation - https://backstage.io/docs/features/kubernetes/troubleshooting: 

"""The Kubernetes tab will not show anything when the catalog info annotation does not match the related Kubernetes resource. We recommend you add the following labels to your resources and use the label selector annotation as follows:

backstage.io/kubernetes-id: <entity-service-name>for get k8s service-related objects. See the plugin code: https://github.com/backstage/backstage/blob/a1f587c/plugins/kubernetes-backend/src/service/KubernetesFetcher.ts#L119"""

**NOTE** Can this a RBAC issue maybe ? We should perhaps curl the backstage api/kubernetes to see if it works too  

![Screenshot 2024-02-01 at 12 27 07](https://github.com/q-shift/backstage-playground/assets/463790/fddd94bc-f447-43f3-82af-9cb9e8edb533)
![Screenshot 2024-02-01 at 12 25 23](https://github.com/q-shift/backstage-playground/assets/463790/37027b2b-d5bc-4e9b-af97-024c63ce400a)
![Screenshot 2024-02-01 at 12 18 22](https://github.com/q-shift/backstage-playground/assets/463790/ebab9fdb-a2c4-4223-a337-7deea16c9bdb)
