### ISSUE TITLE
SERVICE_ACCOUNT_TOKEN env var of the app config qshift template is not set

### ISSUE THREAD

**Issue by cmoulliard** [q-shift/backstage-playground#182]
## Issue

The`SERVICE_ACCOUNT_TOKEN` env var of the app config qshift template is not set as the bash script use as env var
```
KUBERNETES_TOKEN
```
and by consequence the following property is empty
```
kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - url: https://api.qshift.snowdrop.dev:6443 # For in-cluster use: https://kubernetes.default.svc
          name: ocp-qshift
          authProvider: 'serviceAccount'
          skipTLSVerify: true
          skipMetricsLookup: true
          serviceAccountToken: <<<<< EMPTY
```

FYI: @iocanel
