### ISSUE TITLE
Document how to assign the cluster-role admin or cluster to the backstage service account

### ISSUE THREAD

**Issue by cmoulliard** [q-shift/backstage-playground#22]
## TODO

Document how to assign the cluster-role admin or cluster to the backstage service account

![Screenshot 2024-02-05 at 12 20 44](https://github.com/q-shift/backstage-playground/assets/463790/127a423b-0bf0-4f09-8faf-8bf22972aa5e)

App config is:
```
kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - url: https://kubernetes.default.svc
          name: ocp-qshift
          authProvider: 'serviceAccount'
          skipTLSVerify: true
          skipMetricsLookup: true
          serviceAccountToken: "k get secret/my-backstage-token-xtgf6 -n backstage -o go-template='{{.data.token | base64decode}}'"
```
