### ISSUE TITLE
Tekton pipelines are not visible under backstage front ui tab

### ISSUE THREAD

**Issue by cmoulliard** [q-shift/backstage-playground#26]
## Issue

Tekton pipelines are not visible under backstage front ui tab even if the annotations are properly set like the app config

```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-quarkus-app
  description: A cool quarkus app
  annotations:
    argocd/app-name: my-quarkus-app
    backstage.io/kubernetes-id: my-quarkus-app
    backstage.io/kubernetes-namespace: qshift
    backstage.io/source-location: url:https://github.com/ch007m/my-quarkus-app
    janus-idp.io/tekton: my-quarkus-app
    tektonci/build-namespace: qshift
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: ch007m/
spec:
  type: service
  lifecycle: production
  owner: user:default/guest
```

and

```
kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - url: https://api.qshift.snowdrop.dev:6443 # https://kubernetes.default.svc
          name: ocp-qshift
          skipTLSVerify: true
          authProvider: 'serviceAccount'
          skipMetricsLookup: true
          serviceAccountToken: eyJhbGciOiJSUz...7rWahk8Z1orGuyvtzXDt-O76c
  customResources:
    - group: 'tekton.dev'
      apiVersion: 'v1'
      plural: 'pipelineruns'
    - group: 'tekton.dev'
      apiVersion: 'v1'
      plural: 'taskruns'
```

![Screenshot 2024-02-05 at 15 53 48](https://github.com/q-shift/backstage-playground/assets/463790/9c011135-adad-46f1-b6fe-d408823782a4)
