### ISSUE TITLE
PipelineRun name is not unique

### ISSUE THREAD

**Issue by cmoulliard** [q-shift/backstage-playground#71]
## Issue

The PipelineRun name is not unique when we populate the resource using the helm chart

```
// source: https://github.com/q-shift/qshift-templates/blob/main/qshift/templates/quarkus-application/manifests/helm/build-test-push/templates/03-pipelinerun-quarkus-build-test-push.yaml

apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: quarkus-build-test-push
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
```

By consequence, it is not possible within a namespace to create several quarkus applications
